name: Build and deploy WAR app to Azure Web App - Arqui-Soft

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Descargar dependencias Jakarta
      - name: Download Jakarta Servlet API
        run: |
          mkdir -p lib
          wget -O lib/jakarta.servlet-api-5.0.0.jar https://repo1.maven.org/maven2/jakarta/servlet/jakarta.servlet-api/5.0.0/jakarta.servlet-api-5.0.0.jar

      # Preparar estructura de directorios
      - name: Prepare directory structure
        run: |
          mkdir -p build/classes
          mkdir -p build/web/WEB-INF/classes
          mkdir -p build/web/WEB-INF/lib
          mkdir -p dist
          # Crear web directory si no existe
          if [ ! -d "web" ]; then
            mkdir -p web/WEB-INF
            echo '<?xml version="1.0" encoding="UTF-8"?>' > web/WEB-INF/web.xml
            echo '<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee" version="5.0">' >> web/WEB-INF/web.xml
            echo '</web-app>' >> web/WEB-INF/web.xml
          fi

      # Copiar dependencias necesarias para Ant
      - name: Setup Ant dependencies
        run: |
          # Buscar y copiar el CopyLibs task si existe
          find . -name "*copylibstask*" -type f -exec cp {} build/web/WEB-INF/lib/ \; 2>/dev/null || echo "CopyLibs task not found, continuing..."

      # Verificar estructura antes del build
      - name: Debug - List project structure
        run: |
          echo "=== Project structure ==="
          find . -type f -name "*.xml" | head -10
          echo "=== Source files ==="
          find src -name "*.java" | head -5 2>/dev/null || echo "No Java files found in src"
          echo "=== Lib directory ==="
          ls -la lib/ || echo "No lib directory"

      # Build principal sin javadoc para evitar errores
      - name: Build with Ant (skip javadoc)
        run: |
          # Intentar diferentes targets en orden de preferencia
          if ant -q -projecthelp | grep -q "compile"; then
            echo "Running ant compile"
            ant compile
          elif ant -q -projecthelp | grep -q "build"; then
            echo "Running ant build"  
            ant build
          else
            echo "Running default ant target"
            ant
          fi

      # Crear WAR si no se gener칩 autom치ticamente
      - name: Create WAR if needed
        run: |
          if [ ! -f dist/*.war ]; then
            echo "WAR file not found, creating manually..."
            mkdir -p temp-war/WEB-INF/classes
            mkdir -p temp-war/WEB-INF/lib
          
            # Copiar clases compiladas
            if [ -d "build/classes" ]; then
              cp -r build/classes/* temp-war/WEB-INF/classes/ 2>/dev/null || echo "No compiled classes found"
            fi
          
            # Copiar archivos web
            if [ -d "web" ]; then
              cp -r web/* temp-war/ 2>/dev/null || echo "No web files found"
            fi
          
            # Copiar dependencias
            if [ -d "lib" ]; then
              cp lib/*.jar temp-war/WEB-INF/lib/ 2>/dev/null || echo "No lib files found"
            fi
          
            # Crear WAR
            cd temp-war
            jar -cvf ../dist/app.war *
            cd ..
            echo "Created WAR file: dist/app.war"
          fi

      # Verificar que se gener칩 el WAR
      - name: Verify WAR creation
        run: |
          echo "=== Looking for WAR files ==="
          find . -name "*.war" -type f
          echo "=== WAR file details ==="
          ls -la dist/*.war || echo "No WAR files in dist directory"
          echo "=== Dist directory contents ==="
          ls -la dist/ || echo "No dist directory"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'dist/*.war'  # Especificar ubicaci칩n exacta

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Verificar artefacto descargado
      - name: Verify downloaded artifacts
        run: |
          echo "=== Downloaded files ==="
          ls -la
          find . -name "*.war" -type f

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3DB6122B35454AB5A2007255B3F0D31F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AE7CBBE18FB84371A4CBD00589E39485 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D4117EC42ACF46D894BBD1E827B9EFC8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Arqui-Soft'
          slot-name: 'Production'
          package: '*.war'  # Buscar WAR en directorio actual