name: Build and deploy WAR app to Azure Web App - Arqui-Soft

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: List files in web directory
        run: ls -R web
      - name: List files in repo root
        run: ls -R
      - name: Verify WEB-INF path
        run: test -d web/WEB-INF && echo "WEB-INF exists in web/" || echo "WEB-INF NOT found in web/"
      - name: Verify WEB-INF path in build folder
        run: test -d build/web/WEB-INF && echo "WEB-INF exists in build/web/" || echo "WEB-INF NOT found in build/web/"

      - name: Build with Ant
        run: ant -Dlibs.CopyLibs.classpath=build/web/WEB-INF/lib/org-netbeans-modules-java-j2seproject-copylibstask.jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '**/*.war'  # asegúrate que tu build.xml genere un archivo .war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3DB6122B35454AB5A2007255B3F0D31F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AE7CBBE18FB84371A4CBD00589E39485 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D4117EC42ACF46D894BBD1E827B9EFC8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Arqui-Soft'
          slot-name: 'Production'
          package: '**/*.war'
